spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:playground
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true
        format_sql: true
        highlight_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy